#!/usr/bin/env bash
# Configures an Ubuntu server to change IP resolution for localhost and facebook.com

sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts